# Generated by Django 5.0 on 2023-12-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0002_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='0', max_length=200),
            preserve_default=False,
        ),
    ]
